<a href="https://colab.research.google.com/github/yuryychayka09-byte/Data_Analytics-/blob/main/LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

It's a Practical work number two, amd this is start her

In [4]:
albums = {
    'band': [
        'Skillet', 'AC/DC', 'Linkin Park', 'KISS',
        'And One', 'Nirvana', 'Sepultura', 'Metallica'
    ],
    'album': [
        'Awake', 'Back in Black', 'Hybrid Theory', 'Destroyer',
        'Virgin Superstar', 'Nevermind', 'Roots', 'Master of Puppets'
    ],
    'year': [
        2009, 1980, 2000, 1976,
        2000, 1991, 1996, 1986
    ],
    'rating': [
        8.5, 9.6, 9.4, 8.7,
        7.9, 9.5, 8.8, 9.7
    ]
}

df_albums = pd.DataFrame(albums)
df_albums

          band              album  year  rating
0      Skillet              Awake  2009     8.5
1        AC/DC      Back in Black  1980     9.6
2  Linkin Park      Hybrid Theory  2000     9.4
3         KISS          Destroyer  1976     8.7
4      And One   Virgin Superstar  2000     7.9
5      Nirvana          Nevermind  1991     9.5
6    Sepultura              Roots  1996     8.8
7    Metallica  Master of Puppets  1986     9.7

it's were first step

In [7]:
from google.colab import drive
drive.mount('/content/drive')

df_sales = pd.read_csv('/content/drive/MyDrive/Coffe_sales.csv')

df_sales.head()

Mounted at /content/drive

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000

In [8]:
df_sales.info()
df_sales.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hour_of_day  3547 non-null   int64
 1   cash_type    3547 non-null   object
 2   money        3547 non-null   float64
 3   coffee_name  3547 non-null   object
 4   Time_of_Day  3547 non-null   object
 5   Weekday      3547 non-null   object
 6   Month_name   3547 non-null   object
 7   Weekdaysort  3547 non-null   int64
 8   Monthsort    3547 non-null   int64
 9   Date         3547 non-null   object
 10  Time         3547 non-null   object
dtypes: float64(1), int64(3), object(7)
memory usage: 304.9+ KB

       hour_of_day        money  Weekdaysort    Monthsort
count  3547.000000  3547.000000  3547.000000  3547.000000
mean     14.185791    31.645216     3.845785     6.453905
std       4.234010     4.877754     1.971501     3.500754
min       6.000000    18.120000     1.000000     1.000000
25%      10.000000    27.920000     2.000000     3.000000
50%      14.000000    32.820000     4.000000     7.000000
75%      18.000000    35.760000     6.000000    10.000000
max      22.000000    38.700000     7.000000    12.000000

In [9]:
row_iloc = df_sales.iloc[2]
row_loc = df_sales.loc[2]
value = df_sales.loc[5, 'money']

In [10]:
mask_high = df_sales['money'] > 35
high_sales = df_sales[mask_high]
high_sales.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000
6,16,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,16:19:02.756000

In [11]:
sorted_sales = df_sales.sort_values('money', ascending=False)
sorted_sales.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
131,10,card,38.7,Latte,Morning,Sat,Mar,6,3,2024-03-23,10:43:59.559000
133,13,card,38.7,Cappuccino,Afternoon,Sat,Mar,6,3,2024-03-23,13:10:07.661000
134,13,card,38.7,Cocoa,Afternoon,Sat,Mar,6,3,2024-03-23,13:11:12.230000
236,12,card,38.7,Cappuccino,Afternoon,Sun,Apr,7,4,2024-04-14,12:24:39.028000
235,17,card,38.7,Cappuccino,Night,Sat,Apr,6,4,2024-04-13,17:53:19.237000

In [12]:
final = df_sales[df_sales['money'] > 35].sort_values('money', ascending=False)
final.to_csv('/content/drive/MyDrive/filtered_sales.csv', index=False)
print("Файл збережено!")

Файл збережено!

In this work the file Coffe_sales.csv was imported into Google Colab. The table was checked with info() and describe() to see the structure and numbers. Indexing was done with iloc and loc to show the difference between position and label. Filtering was used to keep only rows where money > 35. Sorting was done by the column money in descending order to find the biggest transactions. At the end the results were saved into a new CSV file.

This shows the basic skills of Pandas: import, view, indexing, filtering, sorting, and saving data. These steps are the base for more complex analysis later.

Individual Quest

In [13]:
books = {
    'title': ['Пригоди Шерлока Холмса', 'Біле Ікло', 'Морський Вовк'],
    'author': ['Артур Конан Дойл', 'Джек Лондон', 'Джек Лондон'],
    'year': [1892, 1906, 1904],
    'rating': [9.0, 8.8, 9.1]
}

df_books = pd.DataFrame(books)
df_books

                    title            author  year  rating
0  Пригоди Шерлока Холмса  Артур Конан Дойл  1892     9.0
1               Біле Ікло       Джек Лондон  1906     8.8
2           Морський Вовк       Джек Лондон  1904     9.1

In [14]:
df_sales = pd.read_csv('/content/drive/MyDrive/Coffe_sales.csv')
print(df_sales.head(3))
print(df_sales.tail(3))

   hour_of_day cash_type  money    coffee_name Time_of_Day Weekday Month_name  \
0           10      card   38.7          Latte     Morning     Fri        Mar
1           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar
2           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar

   Weekdaysort  Monthsort        Date             Time
0            5          3  2024-03-01  10:15:50.520000
1            5          3  2024-03-01  12:19:22.539000
2            5          3  2024-03-01  12:20:18.089000
      hour_of_day cash_type  money coffee_name Time_of_Day Weekday Month_name  \
3544           14      card  35.76       Cocoa   Afternoon     Sun        Mar
3545           15      card  25.96   Americano   Afternoon     Sun        Mar
3546           18      card  35.76       Latte       Night     Sun        Mar

      Weekdaysort  Monthsort        Date             Time
3544            7          3  2025-03-23  14:44:16.864000
3545            7          3  2025-03-23  15:47:28.723000
3546            7          3  2025-03-23  18:11:38.635000

In [15]:
cols = df_sales.columns
print(cols)
print(type(cols))

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [16]:
print(df_sales.loc[10, 'coffee_name'])
print(df_sales.iloc[7])

Americano with Milk
hour_of_day                     18
cash_type                     card
money                         33.8
coffee_name    Americano with Milk
Time_of_Day                  Night
Weekday                        Fri
Month_name                     Mar
Weekdaysort                      5
Monthsort                        3
Date                    2024-03-01
Time               18:39:03.580000
Name: 7, dtype: object

In [17]:
card_sales = df_sales[df_sales['cash_type'] == 'card']
print(len(card_sales))

3547

In [18]:
latte_sales = df_sales[(df_sales['coffee_name'] == 'Latte') & (df_sales['money'] > 30)]
print(latte_sales.head(10))

    hour_of_day cash_type  money coffee_name Time_of_Day Weekday Month_name  \
0            10      card   38.7       Latte     Morning     Fri        Mar
4            13      card   38.7       Latte   Afternoon     Fri        Mar
17           10      card   38.7       Latte     Morning     Sun        Mar
26           10      card   38.7       Latte     Morning     Mon        Mar
27           10      card   38.7       Latte     Morning     Mon        Mar
30            9      card   38.7       Latte     Morning     Tue        Mar
31           14      card   38.7       Latte   Afternoon     Tue        Mar
32           17      card   38.7       Latte       Night     Tue        Mar
44           11      card   38.7       Latte     Morning     Thu        Mar
53           18      card   38.7       Latte       Night     Fri        Mar

    Weekdaysort  Monthsort        Date             Time
0             5          3  2024-03-01  10:15:50.520000
4             5          3  2024-03-01  13:48:14.626000
17            7          3  2024-03-03  10:27:18.561000
26            1          3  2024-03-04  10:03:51.994000
27            1          3  2024-03-04  10:54:50.958000
30            2          3  2024-03-05  09:59:52.651000
31            2          3  2024-03-05  14:34:55.963000
32            2          3  2024-03-05  17:34:06.043000
44            4          3  2024-03-07  11:03:58.976000
53            5          3  2024-03-08  18:57:51.451000

In [22]:
df_sales['DateTime'] = pd.to_datetime(df_sales['Date'].astype(str) + ' ' + df_sales['Time'], format='mixed')

In [23]:
card_sales = df_sales[df_sales['cash_type'] == 'card']
print("Number of card transactions:", len(card_sales))

Number of card transactions: 3547

In [24]:
latte_sales = df_sales[(df_sales['coffee_name'] == 'Latte') & (df_sales['money'] > 30)]
print(latte_sales.head(10))

    hour_of_day cash_type  money coffee_name Time_of_Day Weekday Month_name  \
0            10      card   38.7       Latte     Morning     Fri        Mar
4            13      card   38.7       Latte   Afternoon     Fri        Mar
17           10      card   38.7       Latte     Morning     Sun        Mar
26           10      card   38.7       Latte     Morning     Mon        Mar
27           10      card   38.7       Latte     Morning     Mon        Mar
30            9      card   38.7       Latte     Morning     Tue        Mar
31           14      card   38.7       Latte   Afternoon     Tue        Mar
32           17      card   38.7       Latte       Night     Tue        Mar
44           11      card   38.7       Latte     Morning     Thu        Mar
53           18      card   38.7       Latte       Night     Fri        Mar

    Weekdaysort  Monthsort       Date             Time                DateTime
0             5          3 2024-03-01  10:15:50.520000 2024-03-01 10:15:50.520
4             5          3 2024-03-01  13:48:14.626000 2024-03-01 13:48:14.626
17            7          3 2024-03-03  10:27:18.561000 2024-03-03 10:27:18.561
26            1          3 2024-03-04  10:03:51.994000 2024-03-04 10:03:51.994
27            1          3 2024-03-04  10:54:50.958000 2024-03-04 10:54:50.958
30            2          3 2024-03-05  09:59:52.651000 2024-03-05 09:59:52.651
31            2          3 2024-03-05  14:34:55.963000 2024-03-05 14:34:55.963
32            2          3 2024-03-05  17:34:06.043000 2024-03-05 17:34:06.043
44            4          3 2024-03-07  11:03:58.976000 2024-03-07 11:03:58.976
53            5          3 2024-03-08  18:57:51.451000 2024-03-08 18:57:51.451

In [25]:
df_sales['DateTime'] = pd.to_datetime(df_sales['Date'].astype(str) + ' ' + df_sales['Time'], errors='coerce')
sorted_by_datetime = df_sales.sort_values('DateTime')
print(sorted_by_datetime.head(3))

   hour_of_day cash_type  money    coffee_name Time_of_Day Weekday Month_name  \
0           10      card   38.7          Latte     Morning     Fri        Mar
1           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar
2           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar

   Weekdaysort  Monthsort       Date             Time                DateTime
0            5          3 2024-03-01  10:15:50.520000 2024-03-01 10:15:50.520
1            5          3 2024-03-01  12:19:22.539000 2024-03-01 12:19:22.539
2            5          3 2024-03-01  12:20:18.089000 2024-03-01 12:20:18.089

In [26]:
def group_and_sort(df, column):
    counts = df[column].value_counts().sort_values(ascending=False)
    return counts.reset_index().rename(columns={'index': column, column: 'count'})

In [27]:
grouped = group_and_sort(df_sales, 'coffee_name')
print(grouped)

                 count  count
0  Americano with Milk    809
1                Latte    757
2            Americano    564
3           Cappuccino    486
4              Cortado    287
5        Hot Chocolate    276
6                Cocoa    239
7             Espresso    129

In [28]:
grouped.to_csv('/content/drive/MyDrive/grouped_coffee.csv', index=False)

Task 1. A small DataFrame was made with three books. It shows title, author, year, and rating.

Task 2. The file Coffe_sales.csv was loaded. First 3 and last 3 rows were printed.

Task 3. All column names were printed. Their type was checked.

Task 4. With loc one value was selected by label. With iloc one row was selected by position.

Task 5. The table was filtered to keep only rows with cash_type = card. The number of rows was counted.

Task 6. The table was filtered to keep only rows with coffee_name = Latte and money > 30. First 10 rows were shown.

Task 7. A new column DateTime was made from Date and Time. The table was sorted by this column.

Task 8. A function was written to group by a column and sort by count. It was used for coffee_name. The result was saved into CSV.

Conclusion
During the practical work, the main skills of using Pandas library were learned. A DataFrame was created with personal book examples. The dataset Coffe_sales.csv was loaded and explored. Column names were checked, and indexing with loc and iloc was practiced. Filtering was used to select rows by conditions, such as payment type or coffee name with price limits. Sorting was done by date and time after combining columns into one DateTime.

These steps showed how to import, view, filter, sort, and save data in Pandas. The practice gave clear understanding of basic operations with tables and prepared for more complex analysis in the future.