<a href="https://colab.research.google.com/github/yuryychayka09-byte/Data_Analytics-/blob/main/%D0%A7%D0%B0%D0%B9%D0%BA%D0%B0_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/MyDrive/sales.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/sales.csv'

In [5]:
df = pd.read_csv('/content/drive/MyDrive/data_dictionary_songs.csv')

In [6]:
df.head()

         column    type                                        description
0      track_id  string                                    Unique track id
1         genre  string  pop / hiphop / edm / rock / latin / rnb / coun...
2        energy   float                               AUDIO: energy (0-10)
3       valence   float                   AUDIO: positivity/valence (0-10)
4  danceability   float                         AUDIO: danceability (0-10)

In [7]:
print("Розмірність:", df.shape)

Розмірність: (21, 3)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   column       21 non-null     object
 1   type         21 non-null     object
 2   description  21 non-null     object
dtypes: object(3)
memory usage: 636.0+ bytes

In [9]:
df.describe()

          column type      description
count         21   21               21
unique        21    3               21
top     track_id  int  Unique track id
freq           1   10                1

In [10]:
print(df.columns)

Index(['column', 'type', 'description'], dtype='object')

In [13]:
arr = np.array ([10,20,30,40,50])
print ("Masive: ", arr)
print ("tyoe elements: ", arr.dtype)
print ("form masive: ", arr.shape)
arr2 = arr * 2
arr3 = arr + 5

print("Masive after Adding five: ", arr3)
print("Sum: ", arr.sum())
print("Medium: ", arr.mean())
print("Minimal:", arr.min())
print("Maximal:", arr.max())

Masive:  [10 20 30 40 50]
tyoe elements:  int64
form masive:  (5,)
Masive after Adding five:  [15 25 35 45 55]
Sum:  150
Medium:  30.0
Minimal: 10
Maximal: 50